import os
from pathlib import Path

from repopilot_worker.scan import scan


def write(root: Path, rel: str, content: bytes | str = "x = 1\n"):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(content.encode() if isinstance(content, str) else content)
    return p


def build_tree(root: Path, outside: Path):
    # kept
    write(root, "main.py", "print(1)\nprint(2)\n")
    write(root, "pkg/util.go", "package pkg\n")
    write(root, "web/app.ts", "export const a = 1\n")
    write(root, "web/view.tsx", "export const b = 2\n")
    write(root, "web/lib.js", "module.exports = 1\n")
    write(root, "web/mod.mjs", "export {}\n")
    write(root, "docs/README.md", "# title\n\ntext")  # no trailing newline
    write(root, "empty.py", "")
    # ignored dirs
    write(root, "node_modules/dep/index.js", "x")
    write(root, "vendor/lib.go", "package x\n")
    write(root, ".git/config", "x")
    write(root, "build/out.py", "x")
    write(root, "src/__pycache__/m.py", "x")
    # lockfiles and generated
    write(root, "package-lock.json", "{}")
    write(root, "go.sum", "x")
    write(root, "yarn.lock", "x")
    write(root, "app.min.js", "x")
    write(root, "api.pb.go", "package api\n")
    write(root, "svc_pb2.py", "x")
    write(root, "gen_header.go", "// Code generated by protoc. DO NOT EDIT.\npackage x\n")
    write(root, "gen_at.ts", "// @generated\nexport {}\n")
    # binary and too large
    write(root, "blob.py", b"abc\x00def")
    write(root, "big.py", "x = 1\n" * 100_000)
    # unsupported extensions
    write(root, "image.png", b"\x89PNG")
    write(root, "Makefile", "all:\n")
    write(root, "data.json", "{}")
    # symlinks pointing outside the root
    write(outside, "secret.py", "TOKEN = 1\n")
    os.symlink(outside / "secret.py", root / "link.py")
    os.symlink(outside, root / "linked_dir")
    # FIFO named like source: must be skipped without being opened (opening would hang)
    os.mkfifo(root / "pipe.py")


def test_scan_fixture_tree(tmp_path):
    root, outside = tmp_path / "repo", tmp_path / "outside"
    root.mkdir()
    outside.mkdir()
    build_tree(root, outside)

    result = scan(root, max_files=5000, max_file_kb=200)

    assert [f.rel_path for f in result.files] == [
        "docs/README.md", "empty.py", "main.py", "pkg/util.go",
        "web/app.ts", "web/lib.js", "web/mod.mjs", "web/view.tsx",
    ]
    assert result.by_language() == {"go": 1, "javascript": 2, "markdown": 1, "python": 2, "typescript": 2}

    by_path = {f.rel_path: f for f in result.files}
    assert by_path["main.py"].lines == 2
    assert by_path["docs/README.md"].lines == 3  # last line has no newline
    assert by_path["empty.py"].lines == 0
    assert by_path["pkg/util.go"].abs_path == root / "pkg" / "util.go"

    assert dict(result.skipped) == {
        "ignored_dir": 5,   # node_modules, vendor, .git, build, __pycache__
        "lockfile": 3,      # package-lock.json, go.sum, yarn.lock
        "generated": 5,     # app.min.js, api.pb.go, svc_pb2.py, header Code generated, header @generated
        "binary": 1,
        "too_large": 1,
        "unsupported": 4,   # image.png, Makefile, data.json, pipe.py (FIFO)
        "symlink": 2,       # link.py, linked_dir
    }


def test_scan_never_reads_through_symlinks(tmp_path):
    root, outside = tmp_path / "repo", tmp_path / "outside"
    root.mkdir()
    outside.mkdir()
    build_tree(root, outside)
    paths = {f.rel_path for f in scan(root, 5000, 200).files}
    assert "link.py" not in paths
    assert not any(p.startswith("linked_dir") for p in paths)
    assert not any(p.startswith("..") or p.startswith("/") for p in paths)


def test_scan_file_cap(tmp_path):
    for i in range(10):
        write(tmp_path, f"f{i:02d}.py")
    result = scan(tmp_path, max_files=4, max_file_kb=200)
    assert [f.rel_path for f in result.files] == ["f00.py", "f01.py", "f02.py", "f03.py"]
    assert result.skipped["over_file_cap"] == 6


def test_scan_size_limit_boundary(tmp_path):
    write(tmp_path, "exact.py", b"a" * 1024)       # exactly 1 KB: kept
    write(tmp_path, "over.py", b"a" * 1025)        # over: skipped
    result = scan(tmp_path, 100, max_file_kb=1)
    assert [f.rel_path for f in result.files] == ["exact.py"]
    assert result.skipped["too_large"] == 1


def test_scan_is_deterministic(tmp_path):
    root, outside = tmp_path / "repo", tmp_path / "outside"
    root.mkdir()
    outside.mkdir()
    build_tree(root, outside)
    a, b = scan(root, 5000, 200), scan(root, 5000, 200)
    assert [f.rel_path for f in a.files] == [f.rel_path for f in b.files]
    assert dict(a.skipped) == dict(b.skipped)


def test_scan_empty_dir(tmp_path):
    result = scan(tmp_path, 100, 200)
    assert result.files == [] and dict(result.skipped) == {}
